[book]
title = "goxcel Documentation"
authors = ["Ryo Arima"]
language = "en"
src = "src"

[build]
build-dir = "dist"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ryo-arima/goxcel"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ryo-arima/goxcel/edit/main/docs/{path}"

[output.html.search]
enable = true

[output.html.fold]
enable = true
level = 0
